name = "simple-ai-chat"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
CLOUDFLARE_ACCOUNT_ID = "your-account-id-here"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "CONFIG_KV"
preview_id = "20caeabdc8c54b369d4cea94a46ff8b8"
id = "20caeabdc8c54b369d4cea94a46ff8b8"

[[kv_namespaces]]
binding = "SESSIONS_KV"
preview_id = "9053ee51efcd41d491d6160075f7919e"
id = "9053ee51efcd41d491d6160075f7919e"

[[kv_namespaces]]
binding = "CHAT_HISTORY_KV"
preview_id = "d49d9e2936e74d459babae773b2587b0"
id = "d49d9e2936e74d459babae773b2587b0"

# Static Assets configuration (2024 best practice)
[assets]
directory = "./public"